services:
  rng:
    build: rng-elixir
    ports:
      - '8001:80'
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  hasher:
    build: hasher-elixir
    ports:
      - '8002:80'
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  webui:
    build: webui
    ports:
      - '8000:80'
    volumes:
      - './webui/files/:/files/'
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  redis:
    image: redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  worker:
    build: worker-elixir
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
